# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      foo:
        description: Whether to foo
        type: boolean
        required: false
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: |
          if [ ${{ github.event.inputs.foo }} = true ]; then
            echo "The variable is true."
          else
            echo "The variable is not true."
          fi

      - name: Check value
        run: |
          echo "The value is: ${{ github.event.inputs.foo }}"

      - name: Run if foo
        if: ${{ github.event.inputs.foo }}
        run: |
          echo "${{ github.event.inputs.foo }}!"

      - name: Don't run if foo  # Eh, I meant "Run if not foo"
        if: ${{ ! github.event.inputs.foo }}
        run: |
          echo "${{ github.event.inputs.foo }}!"
